### ISSUE TITLE
SDK availability in Maven?

### ISSUE THREAD

**Issue by bartlaarhoven** [crowdin/crowdin-java-client-v1#12]
Could you please please also make this SDK available via Maven? Gradle is probably great, but we don't use it. And if you already have the Gradle settings in place, adding a pom.xml shouldn't be too much work I suppose..? It would really help us! Thanks!

**Comment by Andrulko** [comment]
There is a Maven plugin, but not sure if that's exactly what you need..
https://github.com/exoplatform/crowdin-maven-plugin
http://gazelle.ihe.net/content/crowdin-gazelle-integration

**Comment by bartlaarhoven** [comment]
@Andrulko Thanks! But that's not what I was looking for. The plugins you mention make it possible to update translation files during Maven lifecycle phases.

I'm looking for this current library (crowdin-java-sdk) to be available as a Maven dependency in a project. For that, this repository should have a pom.xml added, uploaded to a repository and (optionally) be made available through Maven Central. That's something the developer should do...

**Comment by ihor-popyk** [comment]
Thanks for request @bartlaarhoven.
I'll do this ASAP

@Andrulko

**Comment by bartlaarhoven** [comment]
Thanks! Any expectations when that would be? @ihor-popyk Is it days/weeks/months?

**Comment by ihor-popyk** [comment]
@bartlaarhoven before tomorrow will be done
sorry and thank you for waiting

**Comment by ihor-popyk** [comment]
#13 
@bartlaarhoven, have added `pom.xml` to support work with Maven

**Comment by bartlaarhoven** [comment]
Okay, and in what Maven repository can I find it?

**Comment by omarduarte** [comment]
@ihor-popyk our company would love to have this as well

**Comment by andrii-bodnar** [comment]
Hi @omarduarte!

Did you consider to use the [API v2 Client](https://github.com/crowdin/crowdin-api-client-java)? It's already available for download via Maven. 

It requires changes in your code if you already using v1 client, but it based on the new Crowdin RESTful API v2 that is more powerful against v1.

**Comment by omarduarte** [comment]
Thanks! I think we can close this issue :D
