### ISSUE TITLE
Do not include destination_folder in API requests

### ISSUE THREAD

**Issue by thc202** [crowdin/crowdin-java-client-v1#16]
This seems to be just a side effect of how the destination folder is passed around in the client (AFAICT, in any case the destination folder should have no relevance to the server side).

I noticed (to my surprise) that the path was being sent while reviewing the API requests (in API > Calls History).

**Comment by yavorysynka** [comment]
Hello!

**dest** parameter is related to the path in your Crowdin project, it represents the folder where your source file should be placed after file upload.

Could you please tell me the project name and provide some details on the matter?

Thank you!

**Comment by rohalskyy** [comment]
Thanks for the clarification. I've just passed your inquiry to our devs for further consideration

**Comment by thc202** [comment]
Thank you.

**Comment by thc202** [comment]
This is no longer an issue to me, no longer happening with the newer API client (https://github.com/crowdin/crowdin-api-client-java), happy if the issue is closed.

**Comment by ira-sem** [comment]
Hi! Thanks for letting us know!
